version: "3.7"

services:
  server:
    build: .
    environment:
      REDIS_URL: redis:6379
    ports:
      - 8080:8080
  redis:
    image: redis:5.0.7
    volumes:
      - redis-data:/data
  ui:
    build:
      context: ./frontend 
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8085:80
    links:
      - server:server
volumes:
  redis-data:
